### ISSUE TITLE
Derivation of Recursive implementation

### ISSUE THREAD

**Issue by mathDR** [AdamStone/hypergeometric#1]
Hello.  Can you comment on your multivariate recursive implementation?  In Fog's original "Calculation Methods for Wallenius' Noncentral Hypergeometric Distribution" he mentions that a multivariate version of the recursive function "becomes complicated and inefficient in the multivariate case."

Do you have a derivation of said method?

Thanks

**Comment by AdamStone** [comment]
Hi @mathDR, unfortunately it's been so long since I worked on this that I don't remember much of the algorithm or implementation details anymore. The closest thing I had to a derivation would be the comments documenting each function in hypergeometric.py, especially p_totals_drawn which tries to explain the recursive part. 

Looking at it now, the basic idea was something like:
1. To get the expectation values you need the probability distribution.
2. To get the probability distribution, find the probability of every possible end state you could arrive at after some fixed number of draws.
3. To find the probability of a particular end state, average the probabilities of all the possible paths to reach that state (e.g. if the end state is 2 red and 1 blue I might draw red-blue-red, red-red-blue, or blue-red-red).
4. To find the probability of a particular path, split it up into the probability of just the last draw, times the probability of drawing the shorter path up to that point (which is where the recursion comes in). 

It gets complicated and inefficient in the sense that it's a pretty brute force approach, and the number of possible paths to consider is roughly something like k^n where n is the number of draws and k is the number of different possible outcomes of a draw (because as you recurse backwards through a given path you can have up to k shorter paths to consider at each step). So it doesn't scale well to large numbers of draws and many different colors in the urn, but I was only interested in cases with three outcomes and those were still manageable.

**Comment by mathDR** [comment]
I see.  That makes perfect sense (i.e. to use it when n_draws is small).

Thanks!
